modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="OldManYounger"
description='''
Creates high-resolution renders of Minecraft game objects.

This is a NeoForge 1.21.1 port of the original Fabric Isometric Renders mod.
'''
logoFile="icon.png"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
